import Navbar from "@/components/Navbar";
import "./globals.css"; // นี่คือคำสั่งสำหรับการใช้ NextAuth.js ในโหมดของลูกค้า
import type { Metadata } from "next"; // นำเข้า React เพื่อใช้ในการสร้างคอมโพเนนต์ React
import { Inter } from "next/font/google"; // นำเข้าคอมโพเนนต์ Link จาก Next.js เพื่อสร้างลิงก์ภายในแอพพลิเคชัน
import { getServerSession } from "next-auth";// นำเข้าฟังก์ชัน signOut และ useSession จาก NextAuth.js เพื่อจัดการเซสชันผู้ใช้และออกจากระบบ
import SessionProvider from "@/utils/SessionProvider";

const inter = Inter({ subsets: ["latin"] });
// ใช้ useSession เพื่อดึงข้อมูลเซสชันของผู้ใช้และเก็บไว้ในตัวแปร session. { data: session } คือการดึงข้อมูลเซสชันและกำหนดให้อยู่ในตัวแปร session
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <Navbar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}// export default Navbar;: สิ่งส่งออกคอมโพเนนต์ Navbar เพื่อให้สามารถนำไปใช้ในส่วนอื่นของแอพพลิเคชัน
